2023-11-30 20:02:22,391:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-30 20:02:22,391:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-30 20:02:22,391:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-30 20:02:22,391:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-11-30 20:02:22,836:INFO:PyCaret ClassificationExperiment
2023-11-30 20:02:22,836:INFO:Logging name: clf-default-name
2023-11-30 20:02:22,836:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-11-30 20:02:22,836:INFO:version 3.1.0
2023-11-30 20:02:22,836:INFO:Initializing setup()
2023-11-30 20:02:22,836:INFO:self.USI: e668
2023-11-30 20:02:22,836:INFO:self._variable_keys: {'X', 'fold_groups_param', 'y_test', 'y', 'target_param', 'n_jobs_param', 'log_plots_param', 'fold_shuffle_param', 'is_multiclass', 'gpu_param', 'exp_name_log', 'fold_generator', 'logging_param', 'data', 'pipeline', 'fix_imbalance', 'X_test', 'y_train', 'idx', '_available_plots', 'memory', 'gpu_n_jobs_param', 'exp_id', 'USI', '_ml_usecase', 'seed', 'X_train', 'html_param'}
2023-11-30 20:02:22,836:INFO:Checking environment
2023-11-30 20:02:22,836:INFO:python_version: 3.8.16
2023-11-30 20:02:22,836:INFO:python_build: ('default', 'Jan 17 2023 16:39:35')
2023-11-30 20:02:22,836:INFO:machine: arm64
2023-11-30 20:02:22,836:INFO:platform: macOS-14.1.1-arm64-arm-64bit
2023-11-30 20:02:22,836:INFO:Memory: svmem(total=17179869184, available=4000415744, percent=76.7, used=5211471872, free=656130048, active=2806857728, inactive=3313270784, wired=2404614144)
2023-11-30 20:02:22,836:INFO:Physical Core: 10
2023-11-30 20:02:22,836:INFO:Logical Core: 10
2023-11-30 20:02:22,836:INFO:Checking libraries
2023-11-30 20:02:22,836:INFO:System:
2023-11-30 20:02:22,836:INFO:    python: 3.8.16 (default, Jan 17 2023, 16:39:35)  [Clang 14.0.6 ]
2023-11-30 20:02:22,836:INFO:executable: /Users/marinus/miniconda3/envs/gpu_venv/bin/python
2023-11-30 20:02:22,836:INFO:   machine: macOS-14.1.1-arm64-arm-64bit
2023-11-30 20:02:22,836:INFO:PyCaret required dependencies:
2023-11-30 20:02:22,837:INFO:                 pip: 23.3.1
2023-11-30 20:02:22,837:INFO:          setuptools: 65.6.3
2023-11-30 20:02:22,837:INFO:             pycaret: 3.1.0
2023-11-30 20:02:22,837:INFO:             IPython: 8.10.0
2023-11-30 20:02:22,837:INFO:          ipywidgets: 8.1.1
2023-11-30 20:02:22,837:INFO:                tqdm: 4.64.1
2023-11-30 20:02:22,837:INFO:               numpy: 1.22.3
2023-11-30 20:02:22,837:INFO:              pandas: 1.5.3
2023-11-30 20:02:22,837:INFO:              jinja2: 3.1.2
2023-11-30 20:02:22,837:INFO:               scipy: 1.10.1
2023-11-30 20:02:22,837:INFO:              joblib: 1.2.0
2023-11-30 20:02:22,837:INFO:             sklearn: 1.2.0
2023-11-30 20:02:22,837:INFO:                pyod: 1.1.0
2023-11-30 20:02:22,837:INFO:            imblearn: 0.11.0
2023-11-30 20:02:22,837:INFO:   category_encoders: 2.6.2
2023-11-30 20:02:22,837:INFO:            lightgbm: 4.1.0
2023-11-30 20:02:22,837:INFO:               numba: 0.56.4
2023-11-30 20:02:22,837:INFO:            requests: 2.28.2
2023-11-30 20:02:22,837:INFO:          matplotlib: 3.7.0
2023-11-30 20:02:22,837:INFO:          scikitplot: 0.3.7
2023-11-30 20:02:22,837:INFO:         yellowbrick: 1.5
2023-11-30 20:02:22,838:INFO:              plotly: 5.12.0
2023-11-30 20:02:22,838:INFO:    plotly-resampler: Not installed
2023-11-30 20:02:22,838:INFO:             kaleido: 0.2.1
2023-11-30 20:02:22,838:INFO:           schemdraw: 0.15
2023-11-30 20:02:22,838:INFO:         statsmodels: 0.14.0
2023-11-30 20:02:22,838:INFO:              sktime: 0.21.1
2023-11-30 20:02:22,838:INFO:               tbats: 1.1.3
2023-11-30 20:02:22,838:INFO:            pmdarima: 2.0.3
2023-11-30 20:02:22,838:INFO:              psutil: 5.9.0
2023-11-30 20:02:22,838:INFO:          markupsafe: 2.1.2
2023-11-30 20:02:22,838:INFO:             pickle5: Not installed
2023-11-30 20:02:22,838:INFO:         cloudpickle: 2.2.1
2023-11-30 20:02:22,838:INFO:         deprecation: 2.1.0
2023-11-30 20:02:22,838:INFO:              xxhash: 3.3.0
2023-11-30 20:02:22,838:INFO:           wurlitzer: 3.0.3
2023-11-30 20:02:22,838:INFO:PyCaret optional dependencies:
2023-11-30 20:02:22,940:INFO:                shap: Not installed
2023-11-30 20:02:22,940:INFO:           interpret: Not installed
2023-11-30 20:02:22,940:INFO:                umap: Not installed
2023-11-30 20:02:22,940:INFO:     ydata_profiling: Not installed
2023-11-30 20:02:22,940:INFO:  explainerdashboard: Not installed
2023-11-30 20:02:22,940:INFO:             autoviz: Not installed
2023-11-30 20:02:22,940:INFO:           fairlearn: Not installed
2023-11-30 20:02:22,940:INFO:          deepchecks: Not installed
2023-11-30 20:02:22,940:INFO:             xgboost: 2.0.1
2023-11-30 20:02:22,940:INFO:            catboost: 1.2.2
2023-11-30 20:02:22,940:INFO:              kmodes: Not installed
2023-11-30 20:02:22,940:INFO:             mlxtend: Not installed
2023-11-30 20:02:22,940:INFO:       statsforecast: Not installed
2023-11-30 20:02:22,940:INFO:        tune_sklearn: Not installed
2023-11-30 20:02:22,940:INFO:                 ray: 2.2.0
2023-11-30 20:02:22,940:INFO:            hyperopt: Not installed
2023-11-30 20:02:22,940:INFO:              optuna: Not installed
2023-11-30 20:02:22,940:INFO:               skopt: Not installed
2023-11-30 20:02:22,940:INFO:              mlflow: Not installed
2023-11-30 20:02:22,940:INFO:              gradio: Not installed
2023-11-30 20:02:22,940:INFO:             fastapi: Not installed
2023-11-30 20:02:22,940:INFO:             uvicorn: 0.21.1
2023-11-30 20:02:22,940:INFO:              m2cgen: Not installed
2023-11-30 20:02:22,940:INFO:           evidently: Not installed
2023-11-30 20:02:22,940:INFO:               fugue: Not installed
2023-11-30 20:02:22,941:INFO:           streamlit: Not installed
2023-11-30 20:02:22,941:INFO:             prophet: Not installed
2023-11-30 20:02:22,941:INFO:None
2023-11-30 20:02:22,941:INFO:Set up data.
2023-11-30 20:02:23,138:INFO:Set up folding strategy.
2023-11-30 20:02:23,138:INFO:Set up train/test split.
2023-11-30 20:02:23,205:INFO:Set up index.
2023-11-30 20:02:23,207:INFO:Assigning column types.
2023-11-30 20:02:23,250:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-11-30 20:02:23,267:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-30 20:02:23,267:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:02:23,281:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:02:23,283:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:02:23,300:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-30 20:02:23,300:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:02:23,311:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:02:23,312:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:02:23,312:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-11-30 20:02:23,330:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:02:23,340:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:02:23,341:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:02:23,359:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:02:23,370:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:02:23,371:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:02:23,371:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-11-30 20:02:23,399:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:02:23,400:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:02:23,428:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:02:23,429:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:02:23,431:INFO:Preparing preprocessing pipeline...
2023-11-30 20:02:23,437:INFO:Set up simple imputation.
2023-11-30 20:02:23,443:INFO:Set up column name cleaning.
2023-11-30 20:02:23,600:INFO:Finished creating preprocessing pipeline.
2023-11-30 20:02:23,603:INFO:Pipeline: Pipeline(memory=FastMemory(location=/var/folders/1_/8tjkkw0s5k7bhzr96pfx40dr0000gn/T/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['GRENDAY_', 'MENTHLTH', 'ORNGDAY_',
                                             'HTIN4', 'WTKG3', 'FC60_',
                                             'CHILDREN', 'MAXVO2_', 'PHYSHLTH',
                                             '_VEGESUM', '_DRNKWEK', 'STRFREQ_',
                                             'VEGEDA1_', 'VEGETAB1', 'STRENGTH',
                                             '_BMI5', 'DROCDY3_', 'BEANDAY_',
                                             'AL...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-11-30 20:02:23,603:INFO:Creating final display dataframe.
2023-11-30 20:02:24,068:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target            _MICHD
2                   Target type            Binary
3           Original data shape      (43268, 346)
4        Transformed data shape      (43268, 346)
5   Transformed train set shape      (30287, 346)
6    Transformed test set shape      (12981, 346)
7              Numeric features               345
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              e668
2023-11-30 20:02:24,102:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:02:24,103:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:02:24,135:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:02:24,136:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:02:24,136:INFO:setup() successfully completed in 1.3s...............
2023-11-30 20:02:24,136:INFO:Initializing compare_models()
2023-11-30 20:02:24,136:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4aabf70>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x2b4aabf70>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-11-30 20:02:24,136:INFO:Checking exceptions
2023-11-30 20:02:24,170:INFO:Preparing display monitor
2023-11-30 20:02:24,211:INFO:Initializing Logistic Regression
2023-11-30 20:02:24,211:INFO:Total runtime is 3.417332967122396e-06 minutes
2023-11-30 20:02:24,212:INFO:SubProcess create_model() called ==================================
2023-11-30 20:02:24,213:INFO:Initializing create_model()
2023-11-30 20:02:24,213:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4aabf70>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x31f230d90>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:02:24,213:INFO:Checking exceptions
2023-11-30 20:02:24,213:INFO:Importing libraries
2023-11-30 20:02:24,214:INFO:Copying training dataset
2023-11-30 20:02:24,295:INFO:Defining folds
2023-11-30 20:02:24,295:INFO:Declaring metric variables
2023-11-30 20:02:24,297:INFO:Importing untrained model
2023-11-30 20:02:24,299:INFO:Logistic Regression Imported successfully
2023-11-30 20:02:24,302:INFO:Starting cross validation
2023-11-30 20:02:24,303:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:00,658:INFO:PyCaret ClassificationExperiment
2023-11-30 20:03:00,658:INFO:Logging name: clf-default-name
2023-11-30 20:03:00,658:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-11-30 20:03:00,658:INFO:version 3.1.0
2023-11-30 20:03:00,658:INFO:Initializing setup()
2023-11-30 20:03:00,658:INFO:self.USI: dd64
2023-11-30 20:03:00,659:INFO:self._variable_keys: {'X', 'fold_groups_param', 'y_test', 'y', 'target_param', 'n_jobs_param', 'log_plots_param', 'fold_shuffle_param', 'is_multiclass', 'gpu_param', 'exp_name_log', 'fold_generator', 'logging_param', 'data', 'pipeline', 'fix_imbalance', 'X_test', 'y_train', 'idx', '_available_plots', 'memory', 'gpu_n_jobs_param', 'exp_id', 'USI', '_ml_usecase', 'seed', 'X_train', 'html_param'}
2023-11-30 20:03:00,659:INFO:Checking environment
2023-11-30 20:03:00,659:INFO:python_version: 3.8.16
2023-11-30 20:03:00,659:INFO:python_build: ('default', 'Jan 17 2023 16:39:35')
2023-11-30 20:03:00,659:INFO:machine: arm64
2023-11-30 20:03:00,659:INFO:platform: macOS-14.1.1-arm64-arm-64bit
2023-11-30 20:03:00,659:INFO:Memory: svmem(total=17179869184, available=4500111360, percent=73.8, used=5554323456, free=1279557632, active=3246931968, inactive=3138125824, wired=2307391488)
2023-11-30 20:03:00,659:INFO:Physical Core: 10
2023-11-30 20:03:00,659:INFO:Logical Core: 10
2023-11-30 20:03:00,659:INFO:Checking libraries
2023-11-30 20:03:00,659:INFO:System:
2023-11-30 20:03:00,659:INFO:    python: 3.8.16 (default, Jan 17 2023, 16:39:35)  [Clang 14.0.6 ]
2023-11-30 20:03:00,659:INFO:executable: /Users/marinus/miniconda3/envs/gpu_venv/bin/python
2023-11-30 20:03:00,659:INFO:   machine: macOS-14.1.1-arm64-arm-64bit
2023-11-30 20:03:00,659:INFO:PyCaret required dependencies:
2023-11-30 20:03:00,659:INFO:                 pip: 23.3.1
2023-11-30 20:03:00,659:INFO:          setuptools: 65.6.3
2023-11-30 20:03:00,659:INFO:             pycaret: 3.1.0
2023-11-30 20:03:00,659:INFO:             IPython: 8.10.0
2023-11-30 20:03:00,659:INFO:          ipywidgets: 8.1.1
2023-11-30 20:03:00,659:INFO:                tqdm: 4.64.1
2023-11-30 20:03:00,659:INFO:               numpy: 1.22.3
2023-11-30 20:03:00,659:INFO:              pandas: 1.5.3
2023-11-30 20:03:00,659:INFO:              jinja2: 3.1.2
2023-11-30 20:03:00,659:INFO:               scipy: 1.10.1
2023-11-30 20:03:00,659:INFO:              joblib: 1.2.0
2023-11-30 20:03:00,659:INFO:             sklearn: 1.2.0
2023-11-30 20:03:00,659:INFO:                pyod: 1.1.0
2023-11-30 20:03:00,659:INFO:            imblearn: 0.11.0
2023-11-30 20:03:00,659:INFO:   category_encoders: 2.6.2
2023-11-30 20:03:00,659:INFO:            lightgbm: 4.1.0
2023-11-30 20:03:00,659:INFO:               numba: 0.56.4
2023-11-30 20:03:00,659:INFO:            requests: 2.28.2
2023-11-30 20:03:00,659:INFO:          matplotlib: 3.7.0
2023-11-30 20:03:00,659:INFO:          scikitplot: 0.3.7
2023-11-30 20:03:00,659:INFO:         yellowbrick: 1.5
2023-11-30 20:03:00,659:INFO:              plotly: 5.12.0
2023-11-30 20:03:00,659:INFO:    plotly-resampler: Not installed
2023-11-30 20:03:00,659:INFO:             kaleido: 0.2.1
2023-11-30 20:03:00,659:INFO:           schemdraw: 0.15
2023-11-30 20:03:00,659:INFO:         statsmodels: 0.14.0
2023-11-30 20:03:00,659:INFO:              sktime: 0.21.1
2023-11-30 20:03:00,659:INFO:               tbats: 1.1.3
2023-11-30 20:03:00,659:INFO:            pmdarima: 2.0.3
2023-11-30 20:03:00,659:INFO:              psutil: 5.9.0
2023-11-30 20:03:00,659:INFO:          markupsafe: 2.1.2
2023-11-30 20:03:00,659:INFO:             pickle5: Not installed
2023-11-30 20:03:00,659:INFO:         cloudpickle: 2.2.1
2023-11-30 20:03:00,659:INFO:         deprecation: 2.1.0
2023-11-30 20:03:00,659:INFO:              xxhash: 3.3.0
2023-11-30 20:03:00,659:INFO:           wurlitzer: 3.0.3
2023-11-30 20:03:00,659:INFO:PyCaret optional dependencies:
2023-11-30 20:03:00,660:INFO:                shap: Not installed
2023-11-30 20:03:00,660:INFO:           interpret: Not installed
2023-11-30 20:03:00,660:INFO:                umap: Not installed
2023-11-30 20:03:00,660:INFO:     ydata_profiling: Not installed
2023-11-30 20:03:00,660:INFO:  explainerdashboard: Not installed
2023-11-30 20:03:00,660:INFO:             autoviz: Not installed
2023-11-30 20:03:00,660:INFO:           fairlearn: Not installed
2023-11-30 20:03:00,660:INFO:          deepchecks: Not installed
2023-11-30 20:03:00,660:INFO:             xgboost: 2.0.1
2023-11-30 20:03:00,660:INFO:            catboost: 1.2.2
2023-11-30 20:03:00,660:INFO:              kmodes: Not installed
2023-11-30 20:03:00,660:INFO:             mlxtend: Not installed
2023-11-30 20:03:00,660:INFO:       statsforecast: Not installed
2023-11-30 20:03:00,660:INFO:        tune_sklearn: Not installed
2023-11-30 20:03:00,660:INFO:                 ray: 2.2.0
2023-11-30 20:03:00,660:INFO:            hyperopt: Not installed
2023-11-30 20:03:00,660:INFO:              optuna: Not installed
2023-11-30 20:03:00,660:INFO:               skopt: Not installed
2023-11-30 20:03:00,660:INFO:              mlflow: Not installed
2023-11-30 20:03:00,660:INFO:              gradio: Not installed
2023-11-30 20:03:00,660:INFO:             fastapi: Not installed
2023-11-30 20:03:00,660:INFO:             uvicorn: 0.21.1
2023-11-30 20:03:00,660:INFO:              m2cgen: Not installed
2023-11-30 20:03:00,660:INFO:           evidently: Not installed
2023-11-30 20:03:00,660:INFO:               fugue: Not installed
2023-11-30 20:03:00,660:INFO:           streamlit: Not installed
2023-11-30 20:03:00,660:INFO:             prophet: Not installed
2023-11-30 20:03:00,660:INFO:None
2023-11-30 20:03:00,660:INFO:Set up data.
2023-11-30 20:03:01,036:INFO:Set up folding strategy.
2023-11-30 20:03:01,037:INFO:Set up train/test split.
2023-11-30 20:03:01,104:INFO:Set up index.
2023-11-30 20:03:01,107:INFO:Assigning column types.
2023-11-30 20:03:01,155:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-11-30 20:03:01,174:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-30 20:03:01,175:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:03:01,186:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:03:01,187:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:03:01,206:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-30 20:03:01,207:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:03:01,218:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:03:01,220:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:03:01,220:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-11-30 20:03:01,239:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:03:01,250:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:03:01,252:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:03:01,271:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:03:01,283:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:03:01,284:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:03:01,284:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-11-30 20:03:01,314:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:03:01,315:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:03:01,346:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:03:01,347:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:03:01,348:INFO:Preparing preprocessing pipeline...
2023-11-30 20:03:01,356:INFO:Set up simple imputation.
2023-11-30 20:03:01,363:INFO:Set up column name cleaning.
2023-11-30 20:03:01,530:INFO:Finished creating preprocessing pipeline.
2023-11-30 20:03:01,533:INFO:Pipeline: Pipeline(memory=FastMemory(location=/var/folders/1_/8tjkkw0s5k7bhzr96pfx40dr0000gn/T/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['GRENDAY_', 'MENTHLTH', 'ORNGDAY_',
                                             'HTIN4', 'WTKG3', 'FC60_',
                                             'CHILDREN', 'MAXVO2_', 'PHYSHLTH',
                                             '_VEGESUM', '_DRNKWEK', 'STRFREQ_',
                                             'VEGEDA1_', 'VEGETAB1', 'STRENGTH',
                                             '_BMI5', 'DROCDY3_', 'BEANDAY_',
                                             'AL...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-11-30 20:03:01,533:INFO:Creating final display dataframe.
2023-11-30 20:03:02,002:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target            _MICHD
2                   Target type            Binary
3           Original data shape      (43268, 346)
4        Transformed data shape      (43268, 346)
5   Transformed train set shape      (30287, 346)
6    Transformed test set shape      (12981, 346)
7              Numeric features               345
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              dd64
2023-11-30 20:03:02,035:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:03:02,036:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:03:02,065:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:03:02,067:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:03:02,067:INFO:setup() successfully completed in 1.41s...............
2023-11-30 20:03:02,067:INFO:Initializing compare_models()
2023-11-30 20:03:02,067:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-11-30 20:03:02,067:INFO:Checking exceptions
2023-11-30 20:03:02,103:INFO:Preparing display monitor
2023-11-30 20:03:02,112:INFO:Initializing Logistic Regression
2023-11-30 20:03:02,113:INFO:Total runtime is 4.597504933675131e-06 minutes
2023-11-30 20:03:02,114:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:02,114:INFO:Initializing create_model()
2023-11-30 20:03:02,114:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:02,114:INFO:Checking exceptions
2023-11-30 20:03:02,115:INFO:Importing libraries
2023-11-30 20:03:02,115:INFO:Copying training dataset
2023-11-30 20:03:02,179:INFO:Defining folds
2023-11-30 20:03:02,179:INFO:Declaring metric variables
2023-11-30 20:03:02,180:INFO:Importing untrained model
2023-11-30 20:03:02,182:INFO:Logistic Regression Imported successfully
2023-11-30 20:03:02,184:INFO:Starting cross validation
2023-11-30 20:03:02,185:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:11,870:INFO:Calculating mean and std
2023-11-30 20:03:11,873:INFO:Creating metrics dataframe
2023-11-30 20:03:11,878:INFO:Uploading results into container
2023-11-30 20:03:11,879:INFO:Uploading model into container now
2023-11-30 20:03:11,879:INFO:_master_model_container: 1
2023-11-30 20:03:11,879:INFO:_display_container: 2
2023-11-30 20:03:11,880:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-11-30 20:03:11,880:INFO:create_model() successfully completed......................................
2023-11-30 20:03:12,065:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:12,065:INFO:Creating metrics dataframe
2023-11-30 20:03:12,069:INFO:Initializing K Neighbors Classifier
2023-11-30 20:03:12,069:INFO:Total runtime is 0.16594998041788736 minutes
2023-11-30 20:03:12,071:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:12,072:INFO:Initializing create_model()
2023-11-30 20:03:12,072:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:12,072:INFO:Checking exceptions
2023-11-30 20:03:12,072:INFO:Importing libraries
2023-11-30 20:03:12,072:INFO:Copying training dataset
2023-11-30 20:03:12,168:INFO:Defining folds
2023-11-30 20:03:12,168:INFO:Declaring metric variables
2023-11-30 20:03:12,170:INFO:Importing untrained model
2023-11-30 20:03:12,172:INFO:K Neighbors Classifier Imported successfully
2023-11-30 20:03:12,175:INFO:Starting cross validation
2023-11-30 20:03:12,177:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:16,748:INFO:Calculating mean and std
2023-11-30 20:03:16,750:INFO:Creating metrics dataframe
2023-11-30 20:03:16,752:INFO:Uploading results into container
2023-11-30 20:03:16,752:INFO:Uploading model into container now
2023-11-30 20:03:16,752:INFO:_master_model_container: 2
2023-11-30 20:03:16,752:INFO:_display_container: 2
2023-11-30 20:03:16,753:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-11-30 20:03:16,753:INFO:create_model() successfully completed......................................
2023-11-30 20:03:16,870:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:16,870:INFO:Creating metrics dataframe
2023-11-30 20:03:16,874:INFO:Initializing Naive Bayes
2023-11-30 20:03:16,874:INFO:Total runtime is 0.24602149724960326 minutes
2023-11-30 20:03:16,875:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:16,875:INFO:Initializing create_model()
2023-11-30 20:03:16,875:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:16,875:INFO:Checking exceptions
2023-11-30 20:03:16,875:INFO:Importing libraries
2023-11-30 20:03:16,875:INFO:Copying training dataset
2023-11-30 20:03:16,945:INFO:Defining folds
2023-11-30 20:03:16,946:INFO:Declaring metric variables
2023-11-30 20:03:16,947:INFO:Importing untrained model
2023-11-30 20:03:16,949:INFO:Naive Bayes Imported successfully
2023-11-30 20:03:16,952:INFO:Starting cross validation
2023-11-30 20:03:16,953:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:17,635:INFO:Calculating mean and std
2023-11-30 20:03:17,638:INFO:Creating metrics dataframe
2023-11-30 20:03:17,644:INFO:Uploading results into container
2023-11-30 20:03:17,645:INFO:Uploading model into container now
2023-11-30 20:03:17,646:INFO:_master_model_container: 3
2023-11-30 20:03:17,646:INFO:_display_container: 2
2023-11-30 20:03:17,647:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-11-30 20:03:17,647:INFO:create_model() successfully completed......................................
2023-11-30 20:03:17,792:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:17,792:INFO:Creating metrics dataframe
2023-11-30 20:03:17,796:INFO:Initializing Decision Tree Classifier
2023-11-30 20:03:17,796:INFO:Total runtime is 0.26139188210169473 minutes
2023-11-30 20:03:17,797:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:17,798:INFO:Initializing create_model()
2023-11-30 20:03:17,798:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:17,798:INFO:Checking exceptions
2023-11-30 20:03:17,798:INFO:Importing libraries
2023-11-30 20:03:17,798:INFO:Copying training dataset
2023-11-30 20:03:17,868:INFO:Defining folds
2023-11-30 20:03:17,868:INFO:Declaring metric variables
2023-11-30 20:03:17,870:INFO:Importing untrained model
2023-11-30 20:03:17,871:INFO:Decision Tree Classifier Imported successfully
2023-11-30 20:03:17,874:INFO:Starting cross validation
2023-11-30 20:03:17,875:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:20,386:INFO:Calculating mean and std
2023-11-30 20:03:20,387:INFO:Creating metrics dataframe
2023-11-30 20:03:20,390:INFO:Uploading results into container
2023-11-30 20:03:20,390:INFO:Uploading model into container now
2023-11-30 20:03:20,391:INFO:_master_model_container: 4
2023-11-30 20:03:20,391:INFO:_display_container: 2
2023-11-30 20:03:20,391:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-11-30 20:03:20,391:INFO:create_model() successfully completed......................................
2023-11-30 20:03:20,504:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:20,504:INFO:Creating metrics dataframe
2023-11-30 20:03:20,508:INFO:Initializing SVM - Linear Kernel
2023-11-30 20:03:20,508:INFO:Total runtime is 0.30660144885381063 minutes
2023-11-30 20:03:20,510:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:20,510:INFO:Initializing create_model()
2023-11-30 20:03:20,510:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:20,510:INFO:Checking exceptions
2023-11-30 20:03:20,510:INFO:Importing libraries
2023-11-30 20:03:20,510:INFO:Copying training dataset
2023-11-30 20:03:20,577:INFO:Defining folds
2023-11-30 20:03:20,577:INFO:Declaring metric variables
2023-11-30 20:03:20,578:INFO:Importing untrained model
2023-11-30 20:03:20,580:INFO:SVM - Linear Kernel Imported successfully
2023-11-30 20:03:20,582:INFO:Starting cross validation
2023-11-30 20:03:20,584:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:24,286:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,536:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,661:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,671:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,773:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,803:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,826:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,841:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,927:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:24,967:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:03:25,076:INFO:Calculating mean and std
2023-11-30 20:03:25,077:INFO:Creating metrics dataframe
2023-11-30 20:03:25,079:INFO:Uploading results into container
2023-11-30 20:03:25,079:INFO:Uploading model into container now
2023-11-30 20:03:25,080:INFO:_master_model_container: 5
2023-11-30 20:03:25,080:INFO:_display_container: 2
2023-11-30 20:03:25,080:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-11-30 20:03:25,080:INFO:create_model() successfully completed......................................
2023-11-30 20:03:25,192:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:25,192:INFO:Creating metrics dataframe
2023-11-30 20:03:25,196:INFO:Initializing Ridge Classifier
2023-11-30 20:03:25,196:INFO:Total runtime is 0.38473304907480876 minutes
2023-11-30 20:03:25,198:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:25,198:INFO:Initializing create_model()
2023-11-30 20:03:25,198:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:25,198:INFO:Checking exceptions
2023-11-30 20:03:25,198:INFO:Importing libraries
2023-11-30 20:03:25,198:INFO:Copying training dataset
2023-11-30 20:03:25,265:INFO:Defining folds
2023-11-30 20:03:25,267:INFO:Declaring metric variables
2023-11-30 20:03:25,268:INFO:Importing untrained model
2023-11-30 20:03:25,273:INFO:Ridge Classifier Imported successfully
2023-11-30 20:03:25,278:INFO:Starting cross validation
2023-11-30 20:03:25,282:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:25,663:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,676:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,692:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,693:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,710:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,717:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,723:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,730:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,746:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,746:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:03:25,857:INFO:Calculating mean and std
2023-11-30 20:03:25,858:INFO:Creating metrics dataframe
2023-11-30 20:03:25,860:INFO:Uploading results into container
2023-11-30 20:03:25,861:INFO:Uploading model into container now
2023-11-30 20:03:25,861:INFO:_master_model_container: 6
2023-11-30 20:03:25,861:INFO:_display_container: 2
2023-11-30 20:03:25,861:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-11-30 20:03:25,861:INFO:create_model() successfully completed......................................
2023-11-30 20:03:25,973:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:25,973:INFO:Creating metrics dataframe
2023-11-30 20:03:25,978:INFO:Initializing Random Forest Classifier
2023-11-30 20:03:25,978:INFO:Total runtime is 0.39776478211085003 minutes
2023-11-30 20:03:25,980:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:25,980:INFO:Initializing create_model()
2023-11-30 20:03:25,980:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:25,980:INFO:Checking exceptions
2023-11-30 20:03:25,980:INFO:Importing libraries
2023-11-30 20:03:25,980:INFO:Copying training dataset
2023-11-30 20:03:26,048:INFO:Defining folds
2023-11-30 20:03:26,048:INFO:Declaring metric variables
2023-11-30 20:03:26,049:INFO:Importing untrained model
2023-11-30 20:03:26,051:INFO:Random Forest Classifier Imported successfully
2023-11-30 20:03:26,054:INFO:Starting cross validation
2023-11-30 20:03:26,055:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:34,959:INFO:Calculating mean and std
2023-11-30 20:03:34,967:INFO:Creating metrics dataframe
2023-11-30 20:03:34,974:INFO:Uploading results into container
2023-11-30 20:03:34,975:INFO:Uploading model into container now
2023-11-30 20:03:34,976:INFO:_master_model_container: 7
2023-11-30 20:03:34,976:INFO:_display_container: 2
2023-11-30 20:03:34,977:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-11-30 20:03:34,978:INFO:create_model() successfully completed......................................
2023-11-30 20:03:35,203:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:35,203:INFO:Creating metrics dataframe
2023-11-30 20:03:35,208:INFO:Initializing Quadratic Discriminant Analysis
2023-11-30 20:03:35,208:INFO:Total runtime is 0.5515867789586385 minutes
2023-11-30 20:03:35,209:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:35,209:INFO:Initializing create_model()
2023-11-30 20:03:35,209:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:35,209:INFO:Checking exceptions
2023-11-30 20:03:35,209:INFO:Importing libraries
2023-11-30 20:03:35,209:INFO:Copying training dataset
2023-11-30 20:03:35,302:INFO:Defining folds
2023-11-30 20:03:35,302:INFO:Declaring metric variables
2023-11-30 20:03:35,304:INFO:Importing untrained model
2023-11-30 20:03:35,306:INFO:Quadratic Discriminant Analysis Imported successfully
2023-11-30 20:03:35,309:INFO:Starting cross validation
2023-11-30 20:03:35,310:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:36,106:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,120:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,132:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,171:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,232:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,248:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,263:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,281:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,283:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:36,311:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:03:37,821:INFO:Calculating mean and std
2023-11-30 20:03:37,824:INFO:Creating metrics dataframe
2023-11-30 20:03:37,830:INFO:Uploading results into container
2023-11-30 20:03:37,830:INFO:Uploading model into container now
2023-11-30 20:03:37,833:INFO:_master_model_container: 8
2023-11-30 20:03:37,833:INFO:_display_container: 2
2023-11-30 20:03:37,836:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-11-30 20:03:37,836:INFO:create_model() successfully completed......................................
2023-11-30 20:03:38,047:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:38,048:INFO:Creating metrics dataframe
2023-11-30 20:03:38,052:INFO:Initializing Ada Boost Classifier
2023-11-30 20:03:38,053:INFO:Total runtime is 0.5990028301874797 minutes
2023-11-30 20:03:38,054:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:38,054:INFO:Initializing create_model()
2023-11-30 20:03:38,054:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:38,054:INFO:Checking exceptions
2023-11-30 20:03:38,054:INFO:Importing libraries
2023-11-30 20:03:38,054:INFO:Copying training dataset
2023-11-30 20:03:38,145:INFO:Defining folds
2023-11-30 20:03:38,145:INFO:Declaring metric variables
2023-11-30 20:03:38,146:INFO:Importing untrained model
2023-11-30 20:03:38,148:INFO:Ada Boost Classifier Imported successfully
2023-11-30 20:03:38,151:INFO:Starting cross validation
2023-11-30 20:03:38,152:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:03:42,170:INFO:Calculating mean and std
2023-11-30 20:03:42,171:INFO:Creating metrics dataframe
2023-11-30 20:03:42,172:INFO:Uploading results into container
2023-11-30 20:03:42,172:INFO:Uploading model into container now
2023-11-30 20:03:42,173:INFO:_master_model_container: 9
2023-11-30 20:03:42,173:INFO:_display_container: 2
2023-11-30 20:03:42,173:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=123)
2023-11-30 20:03:42,173:INFO:create_model() successfully completed......................................
2023-11-30 20:03:42,292:INFO:SubProcess create_model() end ==================================
2023-11-30 20:03:42,292:INFO:Creating metrics dataframe
2023-11-30 20:03:42,297:INFO:Initializing Gradient Boosting Classifier
2023-11-30 20:03:42,298:INFO:Total runtime is 0.6697537978490193 minutes
2023-11-30 20:03:42,299:INFO:SubProcess create_model() called ==================================
2023-11-30 20:03:42,299:INFO:Initializing create_model()
2023-11-30 20:03:42,299:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:03:42,299:INFO:Checking exceptions
2023-11-30 20:03:42,299:INFO:Importing libraries
2023-11-30 20:03:42,299:INFO:Copying training dataset
2023-11-30 20:03:42,368:INFO:Defining folds
2023-11-30 20:03:42,368:INFO:Declaring metric variables
2023-11-30 20:03:42,369:INFO:Importing untrained model
2023-11-30 20:03:42,371:INFO:Gradient Boosting Classifier Imported successfully
2023-11-30 20:03:42,374:INFO:Starting cross validation
2023-11-30 20:03:42,375:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:04:00,076:INFO:Calculating mean and std
2023-11-30 20:04:00,079:INFO:Creating metrics dataframe
2023-11-30 20:04:00,082:INFO:Uploading results into container
2023-11-30 20:04:00,083:INFO:Uploading model into container now
2023-11-30 20:04:00,083:INFO:_master_model_container: 10
2023-11-30 20:04:00,083:INFO:_display_container: 2
2023-11-30 20:04:00,084:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-11-30 20:04:00,084:INFO:create_model() successfully completed......................................
2023-11-30 20:04:00,213:INFO:SubProcess create_model() end ==================================
2023-11-30 20:04:00,213:INFO:Creating metrics dataframe
2023-11-30 20:04:00,218:INFO:Initializing Linear Discriminant Analysis
2023-11-30 20:04:00,218:INFO:Total runtime is 0.9684289137522379 minutes
2023-11-30 20:04:00,220:INFO:SubProcess create_model() called ==================================
2023-11-30 20:04:00,220:INFO:Initializing create_model()
2023-11-30 20:04:00,220:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:04:00,220:INFO:Checking exceptions
2023-11-30 20:04:00,220:INFO:Importing libraries
2023-11-30 20:04:00,220:INFO:Copying training dataset
2023-11-30 20:04:00,293:INFO:Defining folds
2023-11-30 20:04:00,293:INFO:Declaring metric variables
2023-11-30 20:04:00,295:INFO:Importing untrained model
2023-11-30 20:04:00,296:INFO:Linear Discriminant Analysis Imported successfully
2023-11-30 20:04:00,299:INFO:Starting cross validation
2023-11-30 20:04:00,300:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:04:03,494:INFO:Calculating mean and std
2023-11-30 20:04:03,495:INFO:Creating metrics dataframe
2023-11-30 20:04:03,499:INFO:Uploading results into container
2023-11-30 20:04:03,499:INFO:Uploading model into container now
2023-11-30 20:04:03,500:INFO:_master_model_container: 11
2023-11-30 20:04:03,500:INFO:_display_container: 2
2023-11-30 20:04:03,500:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-11-30 20:04:03,500:INFO:create_model() successfully completed......................................
2023-11-30 20:04:03,680:INFO:SubProcess create_model() end ==================================
2023-11-30 20:04:03,680:INFO:Creating metrics dataframe
2023-11-30 20:04:03,685:INFO:Initializing Extra Trees Classifier
2023-11-30 20:04:03,685:INFO:Total runtime is 1.0262153347333272 minutes
2023-11-30 20:04:03,687:INFO:SubProcess create_model() called ==================================
2023-11-30 20:04:03,687:INFO:Initializing create_model()
2023-11-30 20:04:03,687:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:04:03,687:INFO:Checking exceptions
2023-11-30 20:04:03,687:INFO:Importing libraries
2023-11-30 20:04:03,687:INFO:Copying training dataset
2023-11-30 20:04:03,821:INFO:Defining folds
2023-11-30 20:04:03,821:INFO:Declaring metric variables
2023-11-30 20:04:03,822:INFO:Importing untrained model
2023-11-30 20:04:03,824:INFO:Extra Trees Classifier Imported successfully
2023-11-30 20:04:03,827:INFO:Starting cross validation
2023-11-30 20:04:03,828:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:04:17,085:INFO:Calculating mean and std
2023-11-30 20:04:17,091:INFO:Creating metrics dataframe
2023-11-30 20:04:17,109:INFO:Uploading results into container
2023-11-30 20:04:17,109:INFO:Uploading model into container now
2023-11-30 20:04:17,110:INFO:_master_model_container: 12
2023-11-30 20:04:17,110:INFO:_display_container: 2
2023-11-30 20:04:17,111:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-11-30 20:04:17,111:INFO:create_model() successfully completed......................................
2023-11-30 20:04:17,319:INFO:SubProcess create_model() end ==================================
2023-11-30 20:04:17,319:INFO:Creating metrics dataframe
2023-11-30 20:04:17,325:INFO:Initializing Extreme Gradient Boosting
2023-11-30 20:04:17,325:INFO:Total runtime is 1.2535491148630777 minutes
2023-11-30 20:04:17,327:INFO:SubProcess create_model() called ==================================
2023-11-30 20:04:17,327:INFO:Initializing create_model()
2023-11-30 20:04:17,327:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:04:17,327:INFO:Checking exceptions
2023-11-30 20:04:17,327:INFO:Importing libraries
2023-11-30 20:04:17,327:INFO:Copying training dataset
2023-11-30 20:04:17,409:INFO:Defining folds
2023-11-30 20:04:17,409:INFO:Declaring metric variables
2023-11-30 20:04:17,411:INFO:Importing untrained model
2023-11-30 20:04:17,412:INFO:Extreme Gradient Boosting Imported successfully
2023-11-30 20:04:17,415:INFO:Starting cross validation
2023-11-30 20:04:17,416:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:04:20,403:INFO:Calculating mean and std
2023-11-30 20:04:20,405:INFO:Creating metrics dataframe
2023-11-30 20:04:20,409:INFO:Uploading results into container
2023-11-30 20:04:20,409:INFO:Uploading model into container now
2023-11-30 20:04:20,410:INFO:_master_model_container: 13
2023-11-30 20:04:20,410:INFO:_display_container: 2
2023-11-30 20:04:20,411:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic', ...)
2023-11-30 20:04:20,411:INFO:create_model() successfully completed......................................
2023-11-30 20:04:20,539:INFO:SubProcess create_model() end ==================================
2023-11-30 20:04:20,539:INFO:Creating metrics dataframe
2023-11-30 20:04:20,544:INFO:Initializing Light Gradient Boosting Machine
2023-11-30 20:04:20,544:INFO:Total runtime is 1.3071958978970846 minutes
2023-11-30 20:04:20,545:INFO:SubProcess create_model() called ==================================
2023-11-30 20:04:20,546:INFO:Initializing create_model()
2023-11-30 20:04:20,546:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:04:20,546:INFO:Checking exceptions
2023-11-30 20:04:20,546:INFO:Importing libraries
2023-11-30 20:04:20,546:INFO:Copying training dataset
2023-11-30 20:04:20,615:INFO:Defining folds
2023-11-30 20:04:20,615:INFO:Declaring metric variables
2023-11-30 20:04:20,617:INFO:Importing untrained model
2023-11-30 20:04:20,619:INFO:Light Gradient Boosting Machine Imported successfully
2023-11-30 20:04:20,621:INFO:Starting cross validation
2023-11-30 20:04:20,622:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:04:26,727:INFO:Calculating mean and std
2023-11-30 20:04:26,729:INFO:Creating metrics dataframe
2023-11-30 20:04:26,731:INFO:Uploading results into container
2023-11-30 20:04:26,732:INFO:Uploading model into container now
2023-11-30 20:04:26,732:INFO:_master_model_container: 14
2023-11-30 20:04:26,732:INFO:_display_container: 2
2023-11-30 20:04:26,732:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-11-30 20:04:26,732:INFO:create_model() successfully completed......................................
2023-11-30 20:04:26,869:INFO:SubProcess create_model() end ==================================
2023-11-30 20:04:26,869:INFO:Creating metrics dataframe
2023-11-30 20:04:26,874:INFO:Initializing CatBoost Classifier
2023-11-30 20:04:26,875:INFO:Total runtime is 1.4127034823099773 minutes
2023-11-30 20:04:26,876:INFO:SubProcess create_model() called ==================================
2023-11-30 20:04:26,876:INFO:Initializing create_model()
2023-11-30 20:04:26,876:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:04:26,876:INFO:Checking exceptions
2023-11-30 20:04:26,876:INFO:Importing libraries
2023-11-30 20:04:26,877:INFO:Copying training dataset
2023-11-30 20:04:26,967:INFO:Defining folds
2023-11-30 20:04:26,967:INFO:Declaring metric variables
2023-11-30 20:04:26,968:INFO:Importing untrained model
2023-11-30 20:04:26,970:INFO:CatBoost Classifier Imported successfully
2023-11-30 20:04:26,972:INFO:Starting cross validation
2023-11-30 20:04:26,973:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:04:55,486:INFO:Calculating mean and std
2023-11-30 20:04:55,489:INFO:Creating metrics dataframe
2023-11-30 20:04:55,494:INFO:Uploading results into container
2023-11-30 20:04:55,494:INFO:Uploading model into container now
2023-11-30 20:04:55,495:INFO:_master_model_container: 15
2023-11-30 20:04:55,495:INFO:_display_container: 2
2023-11-30 20:04:55,495:INFO:<catboost.core.CatBoostClassifier object at 0x31f249970>
2023-11-30 20:04:55,495:INFO:create_model() successfully completed......................................
2023-11-30 20:04:55,663:INFO:SubProcess create_model() end ==================================
2023-11-30 20:04:55,663:INFO:Creating metrics dataframe
2023-11-30 20:04:55,668:INFO:Initializing Dummy Classifier
2023-11-30 20:04:55,668:INFO:Total runtime is 1.8926007668177287 minutes
2023-11-30 20:04:55,670:INFO:SubProcess create_model() called ==================================
2023-11-30 20:04:55,670:INFO:Initializing create_model()
2023-11-30 20:04:55,670:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x2f34d5f40>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:04:55,670:INFO:Checking exceptions
2023-11-30 20:04:55,670:INFO:Importing libraries
2023-11-30 20:04:55,670:INFO:Copying training dataset
2023-11-30 20:04:55,758:INFO:Defining folds
2023-11-30 20:04:55,759:INFO:Declaring metric variables
2023-11-30 20:04:55,760:INFO:Importing untrained model
2023-11-30 20:04:55,762:INFO:Dummy Classifier Imported successfully
2023-11-30 20:04:55,764:INFO:Starting cross validation
2023-11-30 20:04:55,765:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:04:56,402:INFO:Calculating mean and std
2023-11-30 20:04:56,403:INFO:Creating metrics dataframe
2023-11-30 20:04:56,406:INFO:Uploading results into container
2023-11-30 20:04:56,406:INFO:Uploading model into container now
2023-11-30 20:04:56,407:INFO:_master_model_container: 16
2023-11-30 20:04:56,407:INFO:_display_container: 2
2023-11-30 20:04:56,407:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2023-11-30 20:04:56,407:INFO:create_model() successfully completed......................................
2023-11-30 20:04:56,519:INFO:SubProcess create_model() end ==================================
2023-11-30 20:04:56,519:INFO:Creating metrics dataframe
2023-11-30 20:04:56,528:INFO:Initializing create_model()
2023-11-30 20:04:56,528:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a04e20>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:04:56,528:INFO:Checking exceptions
2023-11-30 20:04:56,529:INFO:Importing libraries
2023-11-30 20:04:56,529:INFO:Copying training dataset
2023-11-30 20:04:56,597:INFO:Defining folds
2023-11-30 20:04:56,597:INFO:Declaring metric variables
2023-11-30 20:04:56,598:INFO:Importing untrained model
2023-11-30 20:04:56,598:INFO:Declaring custom model
2023-11-30 20:04:56,598:INFO:Ridge Classifier Imported successfully
2023-11-30 20:04:56,601:INFO:Cross validation set to False
2023-11-30 20:04:56,601:INFO:Fitting Model
2023-11-30 20:04:57,055:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-11-30 20:04:57,055:INFO:create_model() successfully completed......................................
2023-11-30 20:04:57,225:INFO:_master_model_container: 16
2023-11-30 20:04:57,226:INFO:_display_container: 2
2023-11-30 20:04:57,226:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-11-30 20:04:57,226:INFO:compare_models() successfully completed......................................
2023-11-30 20:15:50,561:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

2023-11-30 20:17:07,570:INFO:PyCaret ClassificationExperiment
2023-11-30 20:17:07,571:INFO:Logging name: clf-default-name
2023-11-30 20:17:07,571:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-11-30 20:17:07,571:INFO:version 3.1.0
2023-11-30 20:17:07,571:INFO:Initializing setup()
2023-11-30 20:17:07,571:INFO:self.USI: 01ef
2023-11-30 20:17:07,571:INFO:self._variable_keys: {'X', 'fold_groups_param', 'y_test', 'y', 'target_param', 'n_jobs_param', 'log_plots_param', 'fold_shuffle_param', 'is_multiclass', 'gpu_param', 'exp_name_log', 'fold_generator', 'logging_param', 'data', 'pipeline', 'fix_imbalance', 'X_test', 'y_train', 'idx', '_available_plots', 'memory', 'gpu_n_jobs_param', 'exp_id', 'USI', '_ml_usecase', 'seed', 'X_train', 'html_param'}
2023-11-30 20:17:07,571:INFO:Checking environment
2023-11-30 20:17:07,571:INFO:python_version: 3.8.16
2023-11-30 20:17:07,571:INFO:python_build: ('default', 'Jan 17 2023 16:39:35')
2023-11-30 20:17:07,571:INFO:machine: arm64
2023-11-30 20:17:07,571:INFO:platform: macOS-14.1.1-arm64-arm-64bit
2023-11-30 20:17:07,571:INFO:Memory: svmem(total=17179869184, available=4345233408, percent=74.7, used=5596610560, free=616300544, active=3270377472, inactive=3726245888, wired=2326233088)
2023-11-30 20:17:07,571:INFO:Physical Core: 10
2023-11-30 20:17:07,571:INFO:Logical Core: 10
2023-11-30 20:17:07,571:INFO:Checking libraries
2023-11-30 20:17:07,571:INFO:System:
2023-11-30 20:17:07,571:INFO:    python: 3.8.16 (default, Jan 17 2023, 16:39:35)  [Clang 14.0.6 ]
2023-11-30 20:17:07,571:INFO:executable: /Users/marinus/miniconda3/envs/gpu_venv/bin/python
2023-11-30 20:17:07,571:INFO:   machine: macOS-14.1.1-arm64-arm-64bit
2023-11-30 20:17:07,571:INFO:PyCaret required dependencies:
2023-11-30 20:17:07,571:INFO:                 pip: 23.3.1
2023-11-30 20:17:07,571:INFO:          setuptools: 65.6.3
2023-11-30 20:17:07,571:INFO:             pycaret: 3.1.0
2023-11-30 20:17:07,571:INFO:             IPython: 8.10.0
2023-11-30 20:17:07,571:INFO:          ipywidgets: 8.1.1
2023-11-30 20:17:07,571:INFO:                tqdm: 4.64.1
2023-11-30 20:17:07,571:INFO:               numpy: 1.22.3
2023-11-30 20:17:07,571:INFO:              pandas: 1.5.3
2023-11-30 20:17:07,571:INFO:              jinja2: 3.1.2
2023-11-30 20:17:07,571:INFO:               scipy: 1.10.1
2023-11-30 20:17:07,571:INFO:              joblib: 1.2.0
2023-11-30 20:17:07,571:INFO:             sklearn: 1.2.0
2023-11-30 20:17:07,571:INFO:                pyod: 1.1.0
2023-11-30 20:17:07,571:INFO:            imblearn: 0.11.0
2023-11-30 20:17:07,571:INFO:   category_encoders: 2.6.2
2023-11-30 20:17:07,571:INFO:            lightgbm: 4.1.0
2023-11-30 20:17:07,571:INFO:               numba: 0.56.4
2023-11-30 20:17:07,571:INFO:            requests: 2.28.2
2023-11-30 20:17:07,571:INFO:          matplotlib: 3.7.0
2023-11-30 20:17:07,571:INFO:          scikitplot: 0.3.7
2023-11-30 20:17:07,571:INFO:         yellowbrick: 1.5
2023-11-30 20:17:07,571:INFO:              plotly: 5.12.0
2023-11-30 20:17:07,571:INFO:    plotly-resampler: Not installed
2023-11-30 20:17:07,571:INFO:             kaleido: 0.2.1
2023-11-30 20:17:07,572:INFO:           schemdraw: 0.15
2023-11-30 20:17:07,572:INFO:         statsmodels: 0.14.0
2023-11-30 20:17:07,572:INFO:              sktime: 0.21.1
2023-11-30 20:17:07,572:INFO:               tbats: 1.1.3
2023-11-30 20:17:07,572:INFO:            pmdarima: 2.0.3
2023-11-30 20:17:07,572:INFO:              psutil: 5.9.0
2023-11-30 20:17:07,572:INFO:          markupsafe: 2.1.2
2023-11-30 20:17:07,572:INFO:             pickle5: Not installed
2023-11-30 20:17:07,572:INFO:         cloudpickle: 2.2.1
2023-11-30 20:17:07,572:INFO:         deprecation: 2.1.0
2023-11-30 20:17:07,572:INFO:              xxhash: 3.3.0
2023-11-30 20:17:07,572:INFO:           wurlitzer: 3.0.3
2023-11-30 20:17:07,572:INFO:PyCaret optional dependencies:
2023-11-30 20:17:07,572:INFO:                shap: Not installed
2023-11-30 20:17:07,572:INFO:           interpret: Not installed
2023-11-30 20:17:07,572:INFO:                umap: Not installed
2023-11-30 20:17:07,572:INFO:     ydata_profiling: Not installed
2023-11-30 20:17:07,572:INFO:  explainerdashboard: Not installed
2023-11-30 20:17:07,572:INFO:             autoviz: Not installed
2023-11-30 20:17:07,572:INFO:           fairlearn: Not installed
2023-11-30 20:17:07,572:INFO:          deepchecks: Not installed
2023-11-30 20:17:07,572:INFO:             xgboost: 2.0.1
2023-11-30 20:17:07,572:INFO:            catboost: 1.2.2
2023-11-30 20:17:07,572:INFO:              kmodes: Not installed
2023-11-30 20:17:07,572:INFO:             mlxtend: Not installed
2023-11-30 20:17:07,572:INFO:       statsforecast: Not installed
2023-11-30 20:17:07,572:INFO:        tune_sklearn: Not installed
2023-11-30 20:17:07,572:INFO:                 ray: 2.2.0
2023-11-30 20:17:07,572:INFO:            hyperopt: Not installed
2023-11-30 20:17:07,572:INFO:              optuna: Not installed
2023-11-30 20:17:07,572:INFO:               skopt: Not installed
2023-11-30 20:17:07,572:INFO:              mlflow: Not installed
2023-11-30 20:17:07,572:INFO:              gradio: Not installed
2023-11-30 20:17:07,572:INFO:             fastapi: Not installed
2023-11-30 20:17:07,572:INFO:             uvicorn: 0.21.1
2023-11-30 20:17:07,572:INFO:              m2cgen: Not installed
2023-11-30 20:17:07,572:INFO:           evidently: Not installed
2023-11-30 20:17:07,572:INFO:               fugue: Not installed
2023-11-30 20:17:07,572:INFO:           streamlit: Not installed
2023-11-30 20:17:07,572:INFO:             prophet: Not installed
2023-11-30 20:17:07,572:INFO:None
2023-11-30 20:17:07,572:INFO:Set up data.
2023-11-30 20:17:07,742:INFO:Set up folding strategy.
2023-11-30 20:17:07,743:INFO:Set up train/test split.
2023-11-30 20:17:07,793:INFO:Set up index.
2023-11-30 20:17:07,795:INFO:Assigning column types.
2023-11-30 20:17:07,830:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-11-30 20:17:07,848:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-30 20:17:07,849:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:17:07,860:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:17:07,861:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:17:07,879:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-11-30 20:17:07,879:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:17:07,890:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:17:07,891:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:17:07,892:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-11-30 20:17:07,910:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:17:07,921:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:17:07,922:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:17:07,940:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-11-30 20:17:07,951:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:17:07,952:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:17:07,952:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-11-30 20:17:07,981:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:17:07,982:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:17:08,011:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:17:08,012:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:17:08,012:INFO:Preparing preprocessing pipeline...
2023-11-30 20:17:08,019:INFO:Set up simple imputation.
2023-11-30 20:17:08,023:INFO:Set up column name cleaning.
2023-11-30 20:17:08,143:INFO:Finished creating preprocessing pipeline.
2023-11-30 20:17:08,146:INFO:Pipeline: Pipeline(memory=FastMemory(location=/var/folders/1_/8tjkkw0s5k7bhzr96pfx40dr0000gn/T/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['GRENDAY_', 'MENTHLTH', 'ORNGDAY_',
                                             'HTIN4', 'WTKG3', 'FC60_',
                                             'CHILDREN', 'MAXVO2_', 'PHYSHLTH',
                                             '_VEGESUM', '_DRNKWEK', 'STRFREQ_',
                                             'VEGEDA1_', 'VEGETAB1', 'STRENGTH',
                                             '_BMI5', 'DROCDY3_', 'BEANDAY_',
                                             'AL...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-11-30 20:17:08,146:INFO:Creating final display dataframe.
2023-11-30 20:17:08,489:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target            _MICHD
2                   Target type            Binary
3           Original data shape      (43268, 257)
4        Transformed data shape      (43268, 257)
5   Transformed train set shape      (30287, 257)
6    Transformed test set shape      (12981, 257)
7              Numeric features               256
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              01ef
2023-11-30 20:17:08,523:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:17:08,524:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:17:08,553:INFO:Soft dependency imported: xgboost: 2.0.1
2023-11-30 20:17:08,555:INFO:Soft dependency imported: catboost: 1.2.2
2023-11-30 20:17:08,555:INFO:setup() successfully completed in 0.99s...............
2023-11-30 20:17:08,560:INFO:Initializing compare_models()
2023-11-30 20:17:08,561:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-11-30 20:17:08,561:INFO:Checking exceptions
2023-11-30 20:17:08,584:INFO:Preparing display monitor
2023-11-30 20:17:08,595:INFO:Initializing Logistic Regression
2023-11-30 20:17:08,595:INFO:Total runtime is 2.7020772298177085e-06 minutes
2023-11-30 20:17:08,596:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:08,596:INFO:Initializing create_model()
2023-11-30 20:17:08,596:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:08,596:INFO:Checking exceptions
2023-11-30 20:17:08,597:INFO:Importing libraries
2023-11-30 20:17:08,597:INFO:Copying training dataset
2023-11-30 20:17:08,645:INFO:Defining folds
2023-11-30 20:17:08,645:INFO:Declaring metric variables
2023-11-30 20:17:08,646:INFO:Importing untrained model
2023-11-30 20:17:08,648:INFO:Logistic Regression Imported successfully
2023-11-30 20:17:08,650:INFO:Starting cross validation
2023-11-30 20:17:08,651:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:18,110:INFO:Calculating mean and std
2023-11-30 20:17:18,113:INFO:Creating metrics dataframe
2023-11-30 20:17:18,120:INFO:Uploading results into container
2023-11-30 20:17:18,120:INFO:Uploading model into container now
2023-11-30 20:17:18,121:INFO:_master_model_container: 1
2023-11-30 20:17:18,121:INFO:_display_container: 2
2023-11-30 20:17:18,122:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-11-30 20:17:18,122:INFO:create_model() successfully completed......................................
2023-11-30 20:17:18,336:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:18,336:INFO:Creating metrics dataframe
2023-11-30 20:17:18,341:INFO:Initializing K Neighbors Classifier
2023-11-30 20:17:18,341:INFO:Total runtime is 0.16244208812713623 minutes
2023-11-30 20:17:18,343:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:18,343:INFO:Initializing create_model()
2023-11-30 20:17:18,343:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:18,343:INFO:Checking exceptions
2023-11-30 20:17:18,343:INFO:Importing libraries
2023-11-30 20:17:18,343:INFO:Copying training dataset
2023-11-30 20:17:18,413:INFO:Defining folds
2023-11-30 20:17:18,413:INFO:Declaring metric variables
2023-11-30 20:17:18,415:INFO:Importing untrained model
2023-11-30 20:17:18,417:INFO:K Neighbors Classifier Imported successfully
2023-11-30 20:17:18,419:INFO:Starting cross validation
2023-11-30 20:17:18,420:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:21,742:INFO:Calculating mean and std
2023-11-30 20:17:21,742:INFO:Creating metrics dataframe
2023-11-30 20:17:21,744:INFO:Uploading results into container
2023-11-30 20:17:21,745:INFO:Uploading model into container now
2023-11-30 20:17:21,745:INFO:_master_model_container: 2
2023-11-30 20:17:21,745:INFO:_display_container: 2
2023-11-30 20:17:21,745:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-11-30 20:17:21,745:INFO:create_model() successfully completed......................................
2023-11-30 20:17:21,862:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:21,862:INFO:Creating metrics dataframe
2023-11-30 20:17:21,866:INFO:Initializing Naive Bayes
2023-11-30 20:17:21,866:INFO:Total runtime is 0.2211890697479248 minutes
2023-11-30 20:17:21,867:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:21,867:INFO:Initializing create_model()
2023-11-30 20:17:21,867:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:21,867:INFO:Checking exceptions
2023-11-30 20:17:21,867:INFO:Importing libraries
2023-11-30 20:17:21,868:INFO:Copying training dataset
2023-11-30 20:17:21,914:INFO:Defining folds
2023-11-30 20:17:21,914:INFO:Declaring metric variables
2023-11-30 20:17:21,916:INFO:Importing untrained model
2023-11-30 20:17:21,917:INFO:Naive Bayes Imported successfully
2023-11-30 20:17:21,920:INFO:Starting cross validation
2023-11-30 20:17:21,921:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:22,493:INFO:Calculating mean and std
2023-11-30 20:17:22,494:INFO:Creating metrics dataframe
2023-11-30 20:17:22,495:INFO:Uploading results into container
2023-11-30 20:17:22,496:INFO:Uploading model into container now
2023-11-30 20:17:22,496:INFO:_master_model_container: 3
2023-11-30 20:17:22,496:INFO:_display_container: 2
2023-11-30 20:17:22,496:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-11-30 20:17:22,496:INFO:create_model() successfully completed......................................
2023-11-30 20:17:22,616:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:22,617:INFO:Creating metrics dataframe
2023-11-30 20:17:22,621:INFO:Initializing Decision Tree Classifier
2023-11-30 20:17:22,621:INFO:Total runtime is 0.2337775707244873 minutes
2023-11-30 20:17:22,623:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:22,623:INFO:Initializing create_model()
2023-11-30 20:17:22,623:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:22,623:INFO:Checking exceptions
2023-11-30 20:17:22,623:INFO:Importing libraries
2023-11-30 20:17:22,623:INFO:Copying training dataset
2023-11-30 20:17:22,671:INFO:Defining folds
2023-11-30 20:17:22,671:INFO:Declaring metric variables
2023-11-30 20:17:22,673:INFO:Importing untrained model
2023-11-30 20:17:22,675:INFO:Decision Tree Classifier Imported successfully
2023-11-30 20:17:22,677:INFO:Starting cross validation
2023-11-30 20:17:22,678:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:24,717:INFO:Calculating mean and std
2023-11-30 20:17:24,718:INFO:Creating metrics dataframe
2023-11-30 20:17:24,721:INFO:Uploading results into container
2023-11-30 20:17:24,721:INFO:Uploading model into container now
2023-11-30 20:17:24,721:INFO:_master_model_container: 4
2023-11-30 20:17:24,721:INFO:_display_container: 2
2023-11-30 20:17:24,721:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-11-30 20:17:24,722:INFO:create_model() successfully completed......................................
2023-11-30 20:17:24,867:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:24,867:INFO:Creating metrics dataframe
2023-11-30 20:17:24,872:INFO:Initializing SVM - Linear Kernel
2023-11-30 20:17:24,873:INFO:Total runtime is 0.27130255301793416 minutes
2023-11-30 20:17:24,875:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:24,876:INFO:Initializing create_model()
2023-11-30 20:17:24,876:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:24,876:INFO:Checking exceptions
2023-11-30 20:17:24,876:INFO:Importing libraries
2023-11-30 20:17:24,876:INFO:Copying training dataset
2023-11-30 20:17:24,934:INFO:Defining folds
2023-11-30 20:17:24,934:INFO:Declaring metric variables
2023-11-30 20:17:24,937:INFO:Importing untrained model
2023-11-30 20:17:24,939:INFO:SVM - Linear Kernel Imported successfully
2023-11-30 20:17:24,942:INFO:Starting cross validation
2023-11-30 20:17:24,943:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:27,282:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:27,523:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:27,565:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:27,586:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:27,695:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:27,881:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:27,919:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:28,021:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:28,183:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:28,214:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1238, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-11-30 20:17:28,326:INFO:Calculating mean and std
2023-11-30 20:17:28,327:INFO:Creating metrics dataframe
2023-11-30 20:17:28,329:INFO:Uploading results into container
2023-11-30 20:17:28,329:INFO:Uploading model into container now
2023-11-30 20:17:28,329:INFO:_master_model_container: 5
2023-11-30 20:17:28,329:INFO:_display_container: 2
2023-11-30 20:17:28,330:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-11-30 20:17:28,330:INFO:create_model() successfully completed......................................
2023-11-30 20:17:28,518:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:28,518:INFO:Creating metrics dataframe
2023-11-30 20:17:28,523:INFO:Initializing Ridge Classifier
2023-11-30 20:17:28,523:INFO:Total runtime is 0.33214720090230304 minutes
2023-11-30 20:17:28,525:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:28,525:INFO:Initializing create_model()
2023-11-30 20:17:28,525:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:28,525:INFO:Checking exceptions
2023-11-30 20:17:28,525:INFO:Importing libraries
2023-11-30 20:17:28,525:INFO:Copying training dataset
2023-11-30 20:17:28,597:INFO:Defining folds
2023-11-30 20:17:28,597:INFO:Declaring metric variables
2023-11-30 20:17:28,599:INFO:Importing untrained model
2023-11-30 20:17:28,600:INFO:Ridge Classifier Imported successfully
2023-11-30 20:17:28,603:INFO:Starting cross validation
2023-11-30 20:17:28,604:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:29,229:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,284:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,308:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,316:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,351:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,367:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,380:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,389:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,425:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,436:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 75, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 302, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 77, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-11-30 20:17:29,547:INFO:Calculating mean and std
2023-11-30 20:17:29,550:INFO:Creating metrics dataframe
2023-11-30 20:17:29,554:INFO:Uploading results into container
2023-11-30 20:17:29,555:INFO:Uploading model into container now
2023-11-30 20:17:29,556:INFO:_master_model_container: 6
2023-11-30 20:17:29,556:INFO:_display_container: 2
2023-11-30 20:17:29,556:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-11-30 20:17:29,556:INFO:create_model() successfully completed......................................
2023-11-30 20:17:29,723:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:29,723:INFO:Creating metrics dataframe
2023-11-30 20:17:29,728:INFO:Initializing Random Forest Classifier
2023-11-30 20:17:29,728:INFO:Total runtime is 0.352231502532959 minutes
2023-11-30 20:17:29,730:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:29,730:INFO:Initializing create_model()
2023-11-30 20:17:29,731:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:29,731:INFO:Checking exceptions
2023-11-30 20:17:29,731:INFO:Importing libraries
2023-11-30 20:17:29,731:INFO:Copying training dataset
2023-11-30 20:17:29,784:INFO:Defining folds
2023-11-30 20:17:29,784:INFO:Declaring metric variables
2023-11-30 20:17:29,786:INFO:Importing untrained model
2023-11-30 20:17:29,787:INFO:Random Forest Classifier Imported successfully
2023-11-30 20:17:29,790:INFO:Starting cross validation
2023-11-30 20:17:29,791:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:38,053:INFO:Calculating mean and std
2023-11-30 20:17:38,056:INFO:Creating metrics dataframe
2023-11-30 20:17:38,060:INFO:Uploading results into container
2023-11-30 20:17:38,060:INFO:Uploading model into container now
2023-11-30 20:17:38,061:INFO:_master_model_container: 7
2023-11-30 20:17:38,061:INFO:_display_container: 2
2023-11-30 20:17:38,061:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-11-30 20:17:38,061:INFO:create_model() successfully completed......................................
2023-11-30 20:17:38,240:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:38,240:INFO:Creating metrics dataframe
2023-11-30 20:17:38,245:INFO:Initializing Quadratic Discriminant Analysis
2023-11-30 20:17:38,245:INFO:Total runtime is 0.49416980346043904 minutes
2023-11-30 20:17:38,246:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:38,246:INFO:Initializing create_model()
2023-11-30 20:17:38,246:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:38,246:INFO:Checking exceptions
2023-11-30 20:17:38,246:INFO:Importing libraries
2023-11-30 20:17:38,246:INFO:Copying training dataset
2023-11-30 20:17:38,315:INFO:Defining folds
2023-11-30 20:17:38,316:INFO:Declaring metric variables
2023-11-30 20:17:38,317:INFO:Importing untrained model
2023-11-30 20:17:38,319:INFO:Quadratic Discriminant Analysis Imported successfully
2023-11-30 20:17:38,321:INFO:Starting cross validation
2023-11-30 20:17:38,322:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:38,883:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:38,892:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:38,964:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:38,994:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:39,010:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:39,011:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:39,018:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:39,062:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:39,062:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:39,091:WARNING:/Users/marinus/miniconda3/envs/gpu_venv/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-11-30 20:17:40,319:INFO:Calculating mean and std
2023-11-30 20:17:40,323:INFO:Creating metrics dataframe
2023-11-30 20:17:40,327:INFO:Uploading results into container
2023-11-30 20:17:40,328:INFO:Uploading model into container now
2023-11-30 20:17:40,329:INFO:_master_model_container: 8
2023-11-30 20:17:40,329:INFO:_display_container: 2
2023-11-30 20:17:40,330:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-11-30 20:17:40,330:INFO:create_model() successfully completed......................................
2023-11-30 20:17:40,527:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:40,527:INFO:Creating metrics dataframe
2023-11-30 20:17:40,533:INFO:Initializing Ada Boost Classifier
2023-11-30 20:17:40,533:INFO:Total runtime is 0.5323151191075642 minutes
2023-11-30 20:17:40,535:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:40,535:INFO:Initializing create_model()
2023-11-30 20:17:40,535:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:40,535:INFO:Checking exceptions
2023-11-30 20:17:40,536:INFO:Importing libraries
2023-11-30 20:17:40,536:INFO:Copying training dataset
2023-11-30 20:17:40,606:INFO:Defining folds
2023-11-30 20:17:40,606:INFO:Declaring metric variables
2023-11-30 20:17:40,608:INFO:Importing untrained model
2023-11-30 20:17:40,609:INFO:Ada Boost Classifier Imported successfully
2023-11-30 20:17:40,612:INFO:Starting cross validation
2023-11-30 20:17:40,613:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:43,512:INFO:Calculating mean and std
2023-11-30 20:17:43,514:INFO:Creating metrics dataframe
2023-11-30 20:17:43,516:INFO:Uploading results into container
2023-11-30 20:17:43,516:INFO:Uploading model into container now
2023-11-30 20:17:43,517:INFO:_master_model_container: 9
2023-11-30 20:17:43,517:INFO:_display_container: 2
2023-11-30 20:17:43,517:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=123)
2023-11-30 20:17:43,517:INFO:create_model() successfully completed......................................
2023-11-30 20:17:43,635:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:43,635:INFO:Creating metrics dataframe
2023-11-30 20:17:43,640:INFO:Initializing Gradient Boosting Classifier
2023-11-30 20:17:43,640:INFO:Total runtime is 0.5840939362843831 minutes
2023-11-30 20:17:43,642:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:43,642:INFO:Initializing create_model()
2023-11-30 20:17:43,642:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:43,642:INFO:Checking exceptions
2023-11-30 20:17:43,642:INFO:Importing libraries
2023-11-30 20:17:43,642:INFO:Copying training dataset
2023-11-30 20:17:43,690:INFO:Defining folds
2023-11-30 20:17:43,690:INFO:Declaring metric variables
2023-11-30 20:17:43,691:INFO:Importing untrained model
2023-11-30 20:17:43,693:INFO:Gradient Boosting Classifier Imported successfully
2023-11-30 20:17:43,695:INFO:Starting cross validation
2023-11-30 20:17:43,696:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:56,633:INFO:Calculating mean and std
2023-11-30 20:17:56,634:INFO:Creating metrics dataframe
2023-11-30 20:17:56,637:INFO:Uploading results into container
2023-11-30 20:17:56,637:INFO:Uploading model into container now
2023-11-30 20:17:56,637:INFO:_master_model_container: 10
2023-11-30 20:17:56,637:INFO:_display_container: 2
2023-11-30 20:17:56,638:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-11-30 20:17:56,638:INFO:create_model() successfully completed......................................
2023-11-30 20:17:56,756:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:56,756:INFO:Creating metrics dataframe
2023-11-30 20:17:56,761:INFO:Initializing Linear Discriminant Analysis
2023-11-30 20:17:56,761:INFO:Total runtime is 0.8027721524238586 minutes
2023-11-30 20:17:56,762:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:56,762:INFO:Initializing create_model()
2023-11-30 20:17:56,762:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:56,762:INFO:Checking exceptions
2023-11-30 20:17:56,762:INFO:Importing libraries
2023-11-30 20:17:56,763:INFO:Copying training dataset
2023-11-30 20:17:56,806:INFO:Defining folds
2023-11-30 20:17:56,807:INFO:Declaring metric variables
2023-11-30 20:17:56,808:INFO:Importing untrained model
2023-11-30 20:17:56,809:INFO:Linear Discriminant Analysis Imported successfully
2023-11-30 20:17:56,812:INFO:Starting cross validation
2023-11-30 20:17:56,813:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:17:59,300:INFO:Calculating mean and std
2023-11-30 20:17:59,304:INFO:Creating metrics dataframe
2023-11-30 20:17:59,310:INFO:Uploading results into container
2023-11-30 20:17:59,311:INFO:Uploading model into container now
2023-11-30 20:17:59,311:INFO:_master_model_container: 11
2023-11-30 20:17:59,311:INFO:_display_container: 2
2023-11-30 20:17:59,312:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-11-30 20:17:59,312:INFO:create_model() successfully completed......................................
2023-11-30 20:17:59,521:INFO:SubProcess create_model() end ==================================
2023-11-30 20:17:59,521:INFO:Creating metrics dataframe
2023-11-30 20:17:59,527:INFO:Initializing Extra Trees Classifier
2023-11-30 20:17:59,528:INFO:Total runtime is 0.8488873203595478 minutes
2023-11-30 20:17:59,529:INFO:SubProcess create_model() called ==================================
2023-11-30 20:17:59,529:INFO:Initializing create_model()
2023-11-30 20:17:59,530:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:17:59,530:INFO:Checking exceptions
2023-11-30 20:17:59,530:INFO:Importing libraries
2023-11-30 20:17:59,530:INFO:Copying training dataset
2023-11-30 20:17:59,606:INFO:Defining folds
2023-11-30 20:17:59,607:INFO:Declaring metric variables
2023-11-30 20:17:59,608:INFO:Importing untrained model
2023-11-30 20:17:59,610:INFO:Extra Trees Classifier Imported successfully
2023-11-30 20:17:59,613:INFO:Starting cross validation
2023-11-30 20:17:59,614:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:18:11,344:INFO:Calculating mean and std
2023-11-30 20:18:11,347:INFO:Creating metrics dataframe
2023-11-30 20:18:11,352:INFO:Uploading results into container
2023-11-30 20:18:11,353:INFO:Uploading model into container now
2023-11-30 20:18:11,354:INFO:_master_model_container: 12
2023-11-30 20:18:11,354:INFO:_display_container: 2
2023-11-30 20:18:11,354:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-11-30 20:18:11,355:INFO:create_model() successfully completed......................................
2023-11-30 20:18:11,568:INFO:SubProcess create_model() end ==================================
2023-11-30 20:18:11,568:INFO:Creating metrics dataframe
2023-11-30 20:18:11,573:INFO:Initializing Extreme Gradient Boosting
2023-11-30 20:18:11,574:INFO:Total runtime is 1.0496509552001951 minutes
2023-11-30 20:18:11,575:INFO:SubProcess create_model() called ==================================
2023-11-30 20:18:11,575:INFO:Initializing create_model()
2023-11-30 20:18:11,575:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:18:11,575:INFO:Checking exceptions
2023-11-30 20:18:11,575:INFO:Importing libraries
2023-11-30 20:18:11,575:INFO:Copying training dataset
2023-11-30 20:18:11,644:INFO:Defining folds
2023-11-30 20:18:11,644:INFO:Declaring metric variables
2023-11-30 20:18:11,646:INFO:Importing untrained model
2023-11-30 20:18:11,648:INFO:Extreme Gradient Boosting Imported successfully
2023-11-30 20:18:11,650:INFO:Starting cross validation
2023-11-30 20:18:11,651:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:18:13,744:INFO:Calculating mean and std
2023-11-30 20:18:13,744:INFO:Creating metrics dataframe
2023-11-30 20:18:13,747:INFO:Uploading results into container
2023-11-30 20:18:13,747:INFO:Uploading model into container now
2023-11-30 20:18:13,747:INFO:_master_model_container: 13
2023-11-30 20:18:13,747:INFO:_display_container: 2
2023-11-30 20:18:13,748:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic', ...)
2023-11-30 20:18:13,748:INFO:create_model() successfully completed......................................
2023-11-30 20:18:13,872:INFO:SubProcess create_model() end ==================================
2023-11-30 20:18:13,872:INFO:Creating metrics dataframe
2023-11-30 20:18:13,878:INFO:Initializing Light Gradient Boosting Machine
2023-11-30 20:18:13,878:INFO:Total runtime is 1.088061455885569 minutes
2023-11-30 20:18:13,880:INFO:SubProcess create_model() called ==================================
2023-11-30 20:18:13,880:INFO:Initializing create_model()
2023-11-30 20:18:13,880:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:18:13,880:INFO:Checking exceptions
2023-11-30 20:18:13,880:INFO:Importing libraries
2023-11-30 20:18:13,881:INFO:Copying training dataset
2023-11-30 20:18:13,930:INFO:Defining folds
2023-11-30 20:18:13,930:INFO:Declaring metric variables
2023-11-30 20:18:13,932:INFO:Importing untrained model
2023-11-30 20:18:13,933:INFO:Light Gradient Boosting Machine Imported successfully
2023-11-30 20:18:13,936:INFO:Starting cross validation
2023-11-30 20:18:13,937:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:18:19,333:INFO:Calculating mean and std
2023-11-30 20:18:19,337:INFO:Creating metrics dataframe
2023-11-30 20:18:19,340:INFO:Uploading results into container
2023-11-30 20:18:19,340:INFO:Uploading model into container now
2023-11-30 20:18:19,341:INFO:_master_model_container: 14
2023-11-30 20:18:19,341:INFO:_display_container: 2
2023-11-30 20:18:19,341:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-11-30 20:18:19,341:INFO:create_model() successfully completed......................................
2023-11-30 20:18:19,466:INFO:SubProcess create_model() end ==================================
2023-11-30 20:18:19,466:INFO:Creating metrics dataframe
2023-11-30 20:18:19,472:INFO:Initializing CatBoost Classifier
2023-11-30 20:18:19,472:INFO:Total runtime is 1.1812885840733844 minutes
2023-11-30 20:18:19,473:INFO:SubProcess create_model() called ==================================
2023-11-30 20:18:19,474:INFO:Initializing create_model()
2023-11-30 20:18:19,474:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:18:19,474:INFO:Checking exceptions
2023-11-30 20:18:19,474:INFO:Importing libraries
2023-11-30 20:18:19,474:INFO:Copying training dataset
2023-11-30 20:18:19,525:INFO:Defining folds
2023-11-30 20:18:19,525:INFO:Declaring metric variables
2023-11-30 20:18:19,527:INFO:Importing untrained model
2023-11-30 20:18:19,529:INFO:CatBoost Classifier Imported successfully
2023-11-30 20:18:19,532:INFO:Starting cross validation
2023-11-30 20:18:19,533:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:18:46,351:INFO:Calculating mean and std
2023-11-30 20:18:46,353:INFO:Creating metrics dataframe
2023-11-30 20:18:46,355:INFO:Uploading results into container
2023-11-30 20:18:46,355:INFO:Uploading model into container now
2023-11-30 20:18:46,355:INFO:_master_model_container: 15
2023-11-30 20:18:46,356:INFO:_display_container: 2
2023-11-30 20:18:46,356:INFO:<catboost.core.CatBoostClassifier object at 0x2f5fb96d0>
2023-11-30 20:18:46,356:INFO:create_model() successfully completed......................................
2023-11-30 20:18:46,543:INFO:SubProcess create_model() end ==================================
2023-11-30 20:18:46,544:INFO:Creating metrics dataframe
2023-11-30 20:18:46,549:INFO:Initializing Dummy Classifier
2023-11-30 20:18:46,549:INFO:Total runtime is 1.6325780351956682 minutes
2023-11-30 20:18:46,551:INFO:SubProcess create_model() called ==================================
2023-11-30 20:18:46,551:INFO:Initializing create_model()
2023-11-30 20:18:46,551:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x321212760>, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:18:46,551:INFO:Checking exceptions
2023-11-30 20:18:46,551:INFO:Importing libraries
2023-11-30 20:18:46,551:INFO:Copying training dataset
2023-11-30 20:18:46,621:INFO:Defining folds
2023-11-30 20:18:46,621:INFO:Declaring metric variables
2023-11-30 20:18:46,622:INFO:Importing untrained model
2023-11-30 20:18:46,624:INFO:Dummy Classifier Imported successfully
2023-11-30 20:18:46,627:INFO:Starting cross validation
2023-11-30 20:18:46,628:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:18:47,330:INFO:Calculating mean and std
2023-11-30 20:18:47,331:INFO:Creating metrics dataframe
2023-11-30 20:18:47,333:INFO:Uploading results into container
2023-11-30 20:18:47,333:INFO:Uploading model into container now
2023-11-30 20:18:47,334:INFO:_master_model_container: 16
2023-11-30 20:18:47,334:INFO:_display_container: 2
2023-11-30 20:18:47,334:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2023-11-30 20:18:47,334:INFO:create_model() successfully completed......................................
2023-11-30 20:18:47,462:INFO:SubProcess create_model() end ==================================
2023-11-30 20:18:47,462:INFO:Creating metrics dataframe
2023-11-30 20:18:47,472:INFO:Initializing create_model()
2023-11-30 20:18:47,472:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:18:47,472:INFO:Checking exceptions
2023-11-30 20:18:47,473:INFO:Importing libraries
2023-11-30 20:18:47,473:INFO:Copying training dataset
2023-11-30 20:18:47,532:INFO:Defining folds
2023-11-30 20:18:47,532:INFO:Declaring metric variables
2023-11-30 20:18:47,532:INFO:Importing untrained model
2023-11-30 20:18:47,532:INFO:Declaring custom model
2023-11-30 20:18:47,533:INFO:SVM - Linear Kernel Imported successfully
2023-11-30 20:18:47,534:INFO:Cross validation set to False
2023-11-30 20:18:47,534:INFO:Fitting Model
2023-11-30 20:18:49,224:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-11-30 20:18:49,225:INFO:create_model() successfully completed......................................
2023-11-30 20:18:49,360:INFO:_master_model_container: 16
2023-11-30 20:18:49,360:INFO:_display_container: 2
2023-11-30 20:18:49,361:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-11-30 20:18:49,361:INFO:compare_models() successfully completed......................................
2023-11-30 20:18:49,380:INFO:Initializing create_model()
2023-11-30 20:18:49,380:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>, estimator=rf, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-11-30 20:18:49,380:INFO:Checking exceptions
2023-11-30 20:18:49,387:INFO:Importing libraries
2023-11-30 20:18:49,387:INFO:Copying training dataset
2023-11-30 20:18:49,435:INFO:Defining folds
2023-11-30 20:18:49,435:INFO:Declaring metric variables
2023-11-30 20:18:49,437:INFO:Importing untrained model
2023-11-30 20:18:49,440:INFO:Random Forest Classifier Imported successfully
2023-11-30 20:18:49,443:INFO:Starting cross validation
2023-11-30 20:18:49,444:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-11-30 20:18:57,991:INFO:Calculating mean and std
2023-11-30 20:18:57,995:INFO:Creating metrics dataframe
2023-11-30 20:18:58,004:INFO:Finalizing model
2023-11-30 20:18:59,043:INFO:Uploading results into container
2023-11-30 20:18:59,044:INFO:Uploading model into container now
2023-11-30 20:18:59,052:INFO:_master_model_container: 17
2023-11-30 20:18:59,052:INFO:_display_container: 3
2023-11-30 20:18:59,052:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-11-30 20:18:59,053:INFO:create_model() successfully completed......................................
2023-11-30 20:18:59,315:INFO:Initializing tune_model()
2023-11-30 20:18:59,315:INFO:tune_model(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False), fold=None, round=4, n_iter=10, custom_grid=None, optimize=Accuracy, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=True, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, return_train_score=False, kwargs={}, self=<pycaret.classification.oop.ClassificationExperiment object at 0x2b4a19250>)
2023-11-30 20:18:59,315:INFO:Checking exceptions
2023-11-30 20:18:59,367:INFO:Copying training dataset
2023-11-30 20:18:59,398:INFO:Checking base model
2023-11-30 20:18:59,398:INFO:Base model : Random Forest Classifier
2023-11-30 20:18:59,400:INFO:Declaring metric variables
2023-11-30 20:18:59,401:INFO:Defining Hyperparameters
2023-11-30 20:18:59,525:INFO:Tuning with n_jobs=-1
2023-11-30 20:18:59,525:INFO:Initializing RandomizedSearchCV
